### ISSUE TITLE
memory backend not working: 'Backend' object has no attribute 'callback'

### ISSUE THREAD

**Issue by jonozzz** [ask/carrot#32]
I'm still trying to find a way to get rid of the ghettoq DB backend and I tried the memory which sounds very close to what I'm looking for. But...

```
[2010-07-05 22:14:41,845: WARNING/MainProcess] Traceback (most recent call last):
[2010-07-05 22:14:41,845: WARNING/MainProcess] File "extra/celery/bin/celeryd.py", line 386, in <module>
[2010-07-05 22:14:41,845: WARNING/MainProcess] main()
[2010-07-05 22:14:41,845: WARNING/MainProcess] File "extra/celery/bin/celeryd.py", line 383, in main
[2010-07-05 22:14:41,846: WARNING/MainProcess] return run_worker(**vars(options))
[2010-07-05 22:14:41,846: WARNING/MainProcess] File "extra/celery/bin/celeryd.py", line 378, in run_worker
[2010-07-05 22:14:41,846: WARNING/MainProcess] return Worker(**options).run()
[2010-07-05 22:14:41,846: WARNING/MainProcess] File "extra/celery/bin/celeryd.py", line 212, in run
[2010-07-05 22:14:41,846: WARNING/MainProcess] self.run_worker()
[2010-07-05 22:14:41,847: WARNING/MainProcess] File "extra/celery/bin/celeryd.py", line 305, in run_worker
[2010-07-05 22:14:41,847: WARNING/MainProcess] worker.start()
[2010-07-05 22:14:41,847: WARNING/MainProcess] File "/usr/lib64/python2.6/site-packages/celery-2.0.0-py2.6.egg/celery/worker/__init__.py", line 198, in start
[2010-07-05 22:14:41,847: WARNING/MainProcess] component.start()
[2010-07-05 22:14:41,847: WARNING/MainProcess] File "/usr/lib64/python2.6/site-packages/celery-2.0.0-py2.6.egg/celery/worker/listener.py", line 235, in start
[2010-07-05 22:14:41,847: WARNING/MainProcess] self.consume_messages()
[2010-07-05 22:14:41,848: WARNING/MainProcess] File "/usr/lib64/python2.6/site-packages/celery-2.0.0-py2.6.egg/celery/worker/listener.py", line 249, in consume_messages
[2010-07-05 22:14:41,848: WARNING/MainProcess] wait_for_message()
[2010-07-05 22:14:41,848: WARNING/MainProcess] File "/usr/lib64/python2.6/site-packages/celery-2.0.0-py2.6.egg/celery/worker/listener.py", line 389, in _mainloop
[2010-07-05 22:14:41,848: WARNING/MainProcess] yield self.connection.drain_events()
[2010-07-05 22:14:41,848: WARNING/MainProcess] File "/usr/lib64/python2.6/site-packages/carrot-0.10.5-py2.6.egg/carrot/connection.py", line 158, in drain_events
[2010-07-05 22:14:41,853: WARNING/MainProcess] return self.connection.drain_events(**kwargs)
[2010-07-05 22:14:41,853: WARNING/MainProcess] File "/usr/lib64/python2.6/site-packages/carrot-0.10.5-py2.6.egg/carrot/backends/queue.py", line 54, in drain_events
[2010-07-05 22:14:41,856: WARNING/MainProcess] self.callback(message)
[2010-07-05 22:14:41,856: WARNING/MainProcess] AttributeError
[2010-07-05 22:14:41,856: WARNING/MainProcess] :
[2010-07-05 22:14:41,856: WARNING/MainProcess] 'Backend' object has no attribute 'callback'
```

**Comment by ask** [comment]
memory backend is used for the celery test suite, but it's very incomplete. I'm currently working on a new version of it.

**Comment by jonozzz** [comment]
Cool, can't wait! So is the "memory" backend going to be an official backend ?

**Comment by jaypipes** [comment]
Hi Ask, is there an update on this issue?  I'm currently running into issues trying to use the memory backend in my unittests (same result as above backtrace).

I see that Celery uses the memory backend successfully in its unittests, but for the life of me, even if I copy the Celery setup code as-is into my unittests, I can't get it to work.

Any help would be most appreciated.

Cheers,
jay
